
default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: db 
  username: app
  password: app_password
  database: instagram_clone_development 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306

development:
  <<: *default
  database: instagram_clone_development


test:
  <<: *default
  database: instagram_clone_test


production:
  primary: &primary_production
    <<: *default
    database: instagram_clone_production
    username: instagram_clone
    password: <%= ENV["INSTAGRAM_CLONE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: instagram_clone_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: instagram_clone_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: instagram_clone_production_cable
    migrations_paths: db/cable_migrat
